package com.example.composeapp.ui.theme

import androidx.compose.ui.graphics.Color

// Light colors
val primaryLight = Color(0xFF57382E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF7E5B4F)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF68493E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF8F6D61)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF655D5A)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDDD2CE)
val onTertiaryContainerLight = Color(0xFF453E3B)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF1E1B1A)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF1E1B1A)
val surfaceVariantLight = Color(0xFFF1DFD9)
val onSurfaceVariantLight = Color(0xFF504440)
val outlineLight = Color(0xFF827470)
val outlineVariantLight = Color(0xFFD4C3BE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF342F2E)
val inverseOnSurfaceLight = Color(0xFFF8EFED)
val inversePrimaryLight = Color(0xFFE9BDAE)

// Dark colors
val primaryDark = Color(0xFFE9BDAE)
val onPrimaryDark = Color(0xFF452920)
val primaryContainerDark = Color(0xFF634338)
val onPrimaryContainerDark = Color(0xFFFFE0D6)
val secondaryDark = Color(0xFFE7BDB0)
val onSecondaryDark = Color(0xFF442A21)
val secondaryContainerDark = Color(0xFF8F6D61)
val onSecondaryContainerDark = Color(0xFFFFFFFF)
val tertiaryDark = Color(0xFFFDF1ED)
val onTertiaryDark = Color(0xFF352F2C)
val tertiaryContainerDark = Color(0xFFD2C7C3)
val onTertiaryContainerDark = Color(0xFF3D3734)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF161312)
val onBackgroundDark = Color(0xFFE9E1DE)
val surfaceDark = Color(0xFF161312)
val onSurfaceDark = Color(0xFFE9E1DE)
val surfaceVariantDark = Color(0xFF504440)
val onSurfaceVariantDark = Color(0xFFD4C3BE)
val outlineDark = Color(0xFF9D8D89)
val outlineVariantDark = Color(0xFF504440)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE9E1DE)
val inverseOnSurfaceDark = Color(0xFF342F2E)
val inversePrimaryDark = Color(0xFF79564B)
